waves: [
          [
            [runner blue, walker red shield, runner green], [walker blue, runner red, walker red]
          ],
          [
            [runner blue, walker red, runner green], [runner blue, walker red, runner green]
          ]
       ]